# Generated by Django 4.1.4 on 2023-05-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='group_id',
            field=models.CharField(default='0', max_length=640, verbose_name='组'),
        ),
    ]
