# Generated by Django 4.1.4 on 2023-05-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
    ]
