# Generated by Django 4.1.7 on 2023-05-24 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_alter_channel_group_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': '个人频道', 'verbose_name_plural': '个人频道'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '聊天室', 'verbose_name_plural': '聊天室'},
        ),
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
        migrations.AlterModelOptions(
            name='lostandfound',
            options={'verbose_name': '物品信息', 'verbose_name_plural': '物品信息'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '聊天离线记录', 'verbose_name_plural': '聊天离线记录'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': '图片信息', 'verbose_name_plural': '图片信息'},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='group_id',
            field=django_mysql.models.ListTextField(models.IntegerField(), size=10),
        ),
        migrations.AlterField(
            model_name='information',
            name='avatar_url',
            field=models.CharField(default='https://picture.daoxuan.cc/image/202301301254377.webp', max_length=200, verbose_name='头像链接'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.CharField(max_length=200, verbose_name='图片链接'),
        ),
    ]
