# Generated by Django 4.1.4 on 2023-05-19 14:39

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_channel_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='group_id',
            field=django_mysql.models.ListTextField(models.IntegerField(), size=10),
        ),
    ]
