# Generated by Django 4.1.4 on 2023-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_channel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='group_id',
            field=models.CharField(default='0', max_length=64, verbose_name='组'),
        ),
    ]
