# Generated by Django 4.1.7 on 2023-05-17 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_channel_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='information',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.CharField(default=1, max_length=200, verbose_name='发消息的人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.CharField(default=1, max_length=200, verbose_name='接收消息的人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='avator_url',
            field=models.CharField(default='https://image.daoxuan.cc/image/202301301254377.webp', max_length=60, verbose_name='头像链接'),
        ),
        migrations.AlterField(
            model_name='information',
            name='name',
            field=models.CharField(default='昵称', max_length=40, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='information',
            name='qq',
            field=models.CharField(default='', max_length=30, verbose_name='qq号'),
        ),
        migrations.AlterField(
            model_name='information',
            name='wechat',
            field=models.CharField(default='', max_length=40, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room_id',
            field=models.CharField(max_length=200, verbose_name='聊天室id'),
        ),
    ]
