# Generated by Django 4.1.4 on 2023-05-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_user_id_channel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='avatar_url',
            field=models.CharField(default='https://picture.daoxuan.cc/image/202301301254377.webp', max_length=200, verbose_name='头像链接'),
        ),
    ]
