# Generated by Django 4.1.4 on 2023-05-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_channel_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='发消息的人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='to_user',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='接收消息的人'),
            preserve_default=False,
        ),
    ]
