# Generated by Django 4.1.4 on 2023-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_message_user_message_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.CharField(max_length=200, verbose_name='发消息的人'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room_id',
            field=models.CharField(max_length=200, verbose_name='聊天室id'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.CharField(max_length=200, verbose_name='接收消息的人'),
        ),
    ]
